### ISSUE TITLE
searches for commands don't work

### ISSUE THREAD

**Issue by adg** [golang/gddo#201]
Godoc knows about vet: http://godoc.org/code.google.com/p/go.tools/cmd/vet

But it can't find it in search: http://godoc.org/?q=vet

I'm guessing this is because it has zero importers, and so its score is zero, but I can't see where in the code the zero scored entries are excluded from the results.

Any pointers @garyburd ?

**Comment by robpike** [comment]
Consider robpike.io/cmd/now. I can search for the full import path and get the godoc page, but if I search for just
   now
I get no results at all. Since half the time I use godoc.org to find the import path, this makes it harder to find go-gettable commands.

Please address this.

**Comment by shurcooL** [comment]
Personally, I never try to search package import paths on godoc.org because it doesn't work well, I only lookup exact import paths.

It does mention "try go-search.org" which finds too many results when you search for "now", but it finds it if you add "robpike":

http://go-search.org/search?q=now+robpike

You can also do a search of sorts locally using `go list .../now`.
