### ISSUE TITLE
Search API should not be case sensitive

### ISSUE THREAD

**Issue by Kapeli** [golang/gddo#233]
The search API seems to be case sensitive.

For example, this works:
http://api.godoc.org/search?q=github.com/PuerkitoBio/goquery

This doesn't:
http://api.godoc.org/search?q=github.com/puerkitobio/goquery

**Comment by garyburd** [comment]
This is not found because of the redirect from puerkitobio to PuerkitoBio.  The [search API code](https://github.com/golang/gddo/blob/bb20f8c58cabb359ba8de621fdd304c020d8c63c/gddo-server/main.go#L601) should check for the redirect and return the redirected document as [is done in the UI](https://github.com/golang/gddo/blob/bb20f8c58cabb359ba8de621fdd304c020d8c63c/gddo-server/main.go#L236-L241).

**Comment by Kapeli** [comment]
Any ETA for a fix? Sorry for my impatience, but I need to know whether or not I can wait for a fix from your end or if I should figure out a workaround in my app and release an update.

**Comment by garyburd** [comment]
I have no plans to work on this issue.
