### ISSUE TITLE
Unrecognized import path

### ISSUE THREAD

**Issue by pierrre** [golang/gddo#250]
See https://godoc.org/github.com/pierrre/imageserver/examples/advanced
`Unrecognized import path "github.com/pierrre/imageserver/testdata" (advanced.go:23:2)`
Is it a bug or a feature?

**Comment by shurcooL** [comment]
When listing Go packages in a Go workspace, the `go` tool (and all other well behaved Go tools) ignores directories and filenames that begin with "." or "_" or are named "testdata". ([Source](https://golang.org/cmd/go/#hdr-Description_of_package_lists).)

However, it's still valid (although probably not a great idea) to have Go packages there that can be imported from other packages, such as what you're doing:

```Go
import imageserver_testdata "github.com/pierrre/imageserver/testdata"
```

It's also likely possible to import other packages that the `go` tool would also ignore, like:

```Go
import (
	"github.com/foo/bar/.git/not/a/great/idea/but/likely/possible"
	"github.com/foo/baz/_ignorethis/also/likely/possible"
	"github.com/foo/baz/testdata/also/likely/possible"
)
```

Since `go` tool is able to compile a package that imports one of the above unusual import paths, godoc should also show docs (but not for the packages being imported).

**Comment by pierrre** [comment]
OK I understand.
Should I rename my "testdata" directory? (it was a good name :sob:)

**Comment by garyburd** [comment]
@pierrre You should rename the directory. The godoc command included with the Go distribution does not list directories with the name "testdata".
