### ISSUE TITLE
godoc.org ignores js-only source files

### ISSUE THREAD

**Issue by flimzy** [golang/gddo#342]
Working with [GopherJS](https://github.com/gopherjs/gopherjs) , I have become aware that godoc.org ignores its 'js' build target, leading to blank/missing docs for source files with a js-only target.  Would it be reasonable to support these?

As an example, [jsbuiltin](https://github.com/gopherjs/jsbuiltin) on godoc.org reports [not found](https://godoc.org/github.com/gopherjs/jsbuiltin).

**Comment by shurcooL** [comment]
As an observation, while the default build context on godoc.org is Linux, it already has support for Windows-only packages (i.e. `// +build windows`).

**Comment by garyburd** [comment]
The server tries the GOOS/GOARCH pairs listed [here](https://github.com/golang/gddo/blob/19e2b0c5a3f2eeb82dd8bd33c348feaefb87478a/doc/builder.go#L455-L459) until it finds one with Go files.

**Comment by shurcooL** [comment]
GopherJS uses `"js"` as the value for `GOARCH` (source [here](https://github.com/gopherjs/gopherjs#general)), and `GOOS` is that of the host operating system (e.g., OS X, Linux or Windows).

Would you be amendable to a PR that adds `{"linux", "js"},` pair at the end of the current list? 

I think that'd be enough as I doubt there will be packages that target js architecture AND also GOOS of something other than linux.

That would allow Go packages that target `js` architecture only to show up in godoc. Here are some screenshots from local testing:

![image](https://cloud.githubusercontent.com/assets/1924134/10629538/78948a30-7784-11e5-8db6-3766f7c08ca6.png)

![image](https://cloud.githubusercontent.com/assets/1924134/10629542/7e2194ac-7784-11e5-834b-bbdaa0398f19.png)

![image](https://cloud.githubusercontent.com/assets/1924134/10629546/84420272-7784-11e5-9f16-9be320cb9940.png)

(It's not as useful on the last 2 packages because they're commands, not libraries. But that's fine, and not related to this issue.)

Without that change, all those packages would display the usual "Not Found" message:

![image](https://cloud.githubusercontent.com/assets/1924134/10629570/b9de954e-7784-11e5-802a-225a6a79090a.png)

**Comment by adg** [comment]
On 21 October 2015 at 17:46, Dmitri Shuralyov <notifications@github.com>
wrote:

> Would you be amendable to a PR that adds {"linux", "js"}, pair at the end
> of the current list?
>

SGTM
