### ISSUE TITLE
Not found for existing package

### ISSUE THREAD

**Issue by AntoineAugusti** [golang/gddo#348]
Hi,

For some reasons, it seems that I cannot add my package on Godoc. Here is my package on GitHub: https://github.com/AntoineAugusti/moduluschecking

And the corresponding link on Godoc shows the 404 page: https://godoc.org/github.com/AntoineAugusti/moduluschecking

Any help would be really appreciated!

**Comment by AntoineAugusti** [comment]
It just appeared after a good 30 minutes...

**Comment by rjeczalik** [comment]
@AntoineAugusti Actually this was just ninja me ;)

There's no `.go` files in the top directory of your package that's why it was responding with 404.

What I did is to navigate on godoc.org to a directory of your package that contains `.go` files, navigate back to its top directory and refresh it. Not sure if it's desirable ux or a workaround.

**Comment by AntoineAugusti** [comment]
@rjeczalik Ah ah, thanks for the ninja fix :+1: Seems like a workaround for me.

You raise another interesting question: how can I add a short sentence to the root of the directory if I don't have any go files? Is it even possible?
