### ISSUE TITLE
Request: Add a better example for Format

### ISSUE THREAD

**Issue by iio7** [golang/gddo#357]
Coming from PHP I really struggled figuring out how to format date output.

In PHP we can simply do this:

```php
$today = date("y-m-d");
```

After some help on IRC I found this solution really simple:

```go
today := time.Now().Format("2006-01-02")
```

I spend a really long time trying to figure that out. Maybe it's just me, but a simple example like this would REALLY help.

**Comment by shurcooL** [comment]
This looks like a general question about Go, and its `time` package. This is an issue tracker for the https://godoc.org/ project.

I suggest you ask your question in the [go-nuts mailing list](https://groups.google.com/forum/#!forum/golang-nuts).

There are some other resources for beginners you might want to look through first (like the FAQ), since your question is a common one.

https://golang.org/help/

**Comment by lucidlime** [comment]
I agree with @shurcooL that this is a question about Go.  If the [current example](https://godoc.org/time#example-Time-Format) does not guide you to solving your specific problem, then file an issue at http://golang.org/issues.
