### ISSUE TITLE
Periods ('.') in package search terms

### ISSUE THREAD

**Issue by yyoon** [golang/gddo#366]
I would like to be able to search for all the packages whose name start with `v.io`, but when I type it in the search box, it searches for just `io` instead.

By looking at the database code, I think this happens because the dot is considered as a term separator, and then `v` is dropped because it's a single character term. Is there any way I could actually search for `v.io` instead?

**Comment by shurcooL** [comment]
I don't know how godoc search works because I almost never use it, but I can think of one workaround.

> Is there any way I could actually search for v.io instead?

This is a really bad workaround, but you could go to the index page, wait for the entire huge thing to load, and then use your browser's find in page functionality to do it:

![image](https://cloud.githubusercontent.com/assets/1924134/12310588/f8e12f9a-ba05-11e5-94f5-abc42c8664ae.png)

**Comment by yyoon** [comment]
Thanks for the comment. However, this is too slow for using regularly. It would be much better if I could search for `v.io` as a single term.
