### ISSUE TITLE
Support inline code using `<code>` like markdown

### ISSUE THREAD

**Issue by mgenware** [golang/gddo#412]
This will make godoc generated text more readable.
Example
```go
// The `HandlerFunc` type is an adapter to allow the use of
// ordinary functions as HTTP handlers.  If `f` is a function
// with the appropriate signature, `HandlerFunc(f)` is a
// Handler that calls `f`.
type HandlerFunc func(ResponseWriter, *Request)
```
Which will be rendered to
// The `HandlerFunc` type is an adapter to allow the use of
// ordinary functions as HTTP handlers.  If `f` is a function
// with the appropriate signature, `HandlerFunc(f)` is a
// Handler that calls `f`.

It's more readable than plain text.

**Comment by shurcooL** [comment]
In general, this is not a bad idea, but implementing it may not trivial and out of scope for this project. Consider the following:

godoc.org follows suit of `godoc` when it comes to figuring out how comments should be parsed and displayed. It adds some minimal and non-invasive enhancements, the kind that would not influence how people write Go documentation whether they target godoc.org or `godoc` command. For example, addling links to RFC spec mentions.

This would be an invasive change, since it'd change how people write comments if they want a certain appearance on godoc.org. Worse yet, it may have unintended false positives where someone has backticks in their docs for other purposes, which would be rendered okay by `godoc` command, but not correctly on godoc.org.

If you want to suggest this change to be done, you'd have to suggest it for the Go project itself. If it's accepted there, godoc.org will need to be updated to match.

This has been suggested in the past and closed for the same reason. Please see https://github.com/golang/gddo/pull/312. I'll close this since it's a duplicate and for the above reasons.

**Comment by adg** [comment]
godoc.org renders godoc comments, and godoc doesn't support markdown. This is a design goal of the tool; good [godoc comments should read like regular comments](https://blog.golang.org/godoc-documenting-go-code).

**Comment by lyda** [comment]
It's a shame this wasn't given further consideration. The use of backticks for inline code is used in Slack, Teams and a number of other places. It's kind of understood to mean "this is a short bit of code here" by most readers.
