### ISSUE TITLE
https://godoc.org/-/index gives a 500

### ISSUE THREAD

**Issue by skeswa** [golang/gddo#451]
This has been the case for a little while. Anyone know what's going on?

**Comment by stephenmw** [comment]
Yeah, this is my fault, I will try to "fix" it tomorrow afternoon by removing it.

Why remove it? The same reason I made it 500, it took down the site because it loads too much into memory. I had to do an emergency push with it disabled to bring the site back up. Actually, I meant to break it in a nicer way than just saying "Internal Server Error", but I screwed up and didn't feel like fixing the break :-P.

**Comment by shurcooL** [comment]
In that case, this is related to issues:

- https://github.com/golang/gddo/issues/407
- https://github.com/golang/gddo/issues/190 (which was closed because it was expected to be resolved soon via other changes, not because it was actually resolved)

**Comment by shantuo** [comment]
Mailed https://go-review.googlesource.com/c/32550/
