### ISSUE TITLE
"server certificate verification failed" for https://godoc.org in Ubuntu 16.10.

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#462]
If I run a vanilla Ubuntu 16.10 virtual machine via a live disk, and run `curl https://godoc.org`, it fails because of a certificate verification failure:

![image](https://cloud.githubusercontent.com/assets/1924134/21373581/06df9cb2-c6ee-11e6-87f6-643111b8e664.png)

As a result, I'm not able to access the godoc.org API endpoint at https://api.godoc.org either.

I'm not sure if the issue is on my end, or on godoc.org. Any thoughts?

**Comment by stephenmw** [comment]
I just uploaded a new cert. Works on chrome. I am afk. Will look in 30 minutes.On Dec 20, 2016 7:44 PM, Dmitri Shuralyov <notifications@github.com> wrote:If I run a vanilla Ubuntu 16.10 virtual machine via a live disk, and run curl https://godoc.org, it fails because of a certificate verification failure:

As a result, I'm not able to access the godoc.org API endpoint at https://api.godoc.org either.
I'm not sure if the issue is on my end on godoc.org, any ideas?

**Comment by stephenmw** [comment]
I can confirm this is happening on a pure version of Debian Jessie. I am working on fixing it. It works fine on my desktop as well as chrome which is very annoying.

**Comment by stephenmw** [comment]
Fixed. I uploaded the full chain this time. Thank you for the bug report. Note: you may get some errors because of caching, if you still see problems in an hour, reopen the bug.

**Comment by shurcooL** [comment]
I can confirm the issue is resolved for me. Thank you!
