### ISSUE TITLE
godoc.org does not show docs when test package name differs from main package name.

### ISSUE THREAD

**Issue by muly** [golang/gddo#466]
I renamed my repo from `github.com/muly/aeunittest` to `github.com/muly/aeinttest`, and since then godoc.org is not showing documentation for my library. I'm getting `No packages found.` error. Before rename, godoc.org was able to find my library. Initially I thought its syncing issue, and waited for a while to see if I works, but it did not. Is this a known issue, and is there a work around? Thanks.

**Comment by shurcooL** [comment]
```
2017/01/02 19:04:25 web   fetch: 509 err: found packages aeunittest (aeunittest_test.go) and aeinttest (testcase.go) in . notfound: no Go files or subdirs github.com/muly/aeinttest
```

It happens because there's a build error for your new package. Specifically, [aeunittest_test.go](https://github.com/muly/aeinttest/blob/9a08ed449cd20d89ef7137a3360c2e6ea67cbb97/aeunittest_test.go) file has `package aeunittest`, but [testcase.go](https://github.com/muly/aeinttest/blob/9a08ed449cd20d89ef7137a3360c2e6ea67cbb97/testcase.go) file has `package aeinttest`.

As a result, there are no valid Go packages to display, and it shows the generic "No packages found" error.

You should fix your bug of course. But gddo could be potentially improved to handle this situation better. Perhaps a more descriptive error message can be shown. Alternatively, we can consider having test files be ignored when displaying documentation, but I'm not sure if that's a good idea.

**Comment by muly** [comment]
thank you. I remember fixing that issue with my code, but is was not pushed to main branch. Now I did it , and I see the package documentation. Thanks a lot.

**Comment by shurcooL** [comment]
Do you think we should still try to do any of the following for godoc.org?

> But gddo could be potentially improved to handle this situation better. Perhaps a more descriptive error message can be shown. Alternatively, we can consider having test files be ignored when displaying documentation, but I'm not sure if that's a good idea.
