### ISSUE TITLE
Server error during open http://talks.golang.org

### ISSUE THREAD

**Issue by andriisoldatenko** [golang/gddo#487]
curl http://talks.golang.org/

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>503 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The service you requested is not available yet.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

**Comment by shurcooL** [comment]
Looks like a temporary error, it works fine for me now.

I'll close this issue because this is the wrong issue tracker. gddo repo contains [talksapp](https://github.com/golang/gddo/tree/master/talksapp), which is https://go-talks.appspot.com/. But https://talks.golang.org/ is related to `golang.org/x/talks`.

If the issue persists, reopen it in the Go issue tracker at https://github.com/golang/go/issues.
