### ISSUE TITLE
logging/v1beta3 missing

### ISSUE THREAD

**Issue by DavidVaini** [golang/gddo#491]
we have code deps that use google.golang.org/api/logging/v1beta3
There are also docs that reference it.But it seems to be missing.

If you go here:
https://godoc.org/google.golang.org/api/logging

It seems like the version is missing entirely.

**Comment by shurcooL** [comment]
There's no issue in gddo project.

godoc.org displays "Not Found" for `google.golang.org/api/logging/v1beta3` import path because that package no longer exists:

https://code.googlesource.com/google-api-go-client/+/master/logging/

It was removed in commit [324744a33f1f37e63dd1695cfb3ec9a3e4a1cb05](https://code.googlesource.com/google-api-go-client/+/324744a33f1f37e63dd1695cfb3ec9a3e4a1cb05).

If you do:

```
$ curl -s 'https://google.golang.org/api/logging?go-get=1' | grep go-import
<meta name="go-import" content="google.golang.org/api git https://code.googlesource.com/google-api-go-client">
```

You can see that https://code.googlesource.com/google-api-go-client is the real source of the `google.golang.org/api/...` packages. The GitHub repository at https://github.com/google/google-api-go-client is just a mirror.

It seems there's some issue with the mirroring, the github repo's [latest commit](https://github.com/google/google-api-go-client/commits/master) is from 18 days ago:

![image](https://user-images.githubusercontent.com/1924134/27488929-c74dfdf0-5806-11e7-99a2-057004f594e0.png)

But the real repository has [5 commits](https://code.googlesource.com/google-api-go-client/+log/HEAD) since then:

![image](https://user-images.githubusercontent.com/1924134/27489009-0004e866-5807-11e7-89f7-71898e430ac0.png)

**Comment by shurcooL** [comment]
If you want, you can/should report the issue of the GitHub mirror repo not being synced properly, but I don't know who/where to report that. Maybe one of the owners of the `google.golang.org/api/...` packages?
