### ISSUE TITLE
gosrc: error importing package from a directory

### ISSUE THREAD

**Issue by shantuo** [golang/gddo#504]
```
cannot find package "." in:
	.
```

This currently blocks new deploying in Go 1.9.

**Comment by shurcooL** [comment]
I think this might be because of my change. I can investigate if no one is already looking.

**Comment by shurcooL** [comment]
@shantuo, you said:

> This currently blocks new deploying in Go 1.9.

Yet I see that the new identifiers from Go 1.9 are already available, e.g., https://godoc.org/encoding/json#Valid is there (it's new to Go 1.9). Did you deploy Go 1.9 or not? If not, how is it showing up?

**Comment by shurcooL** [comment]
> I suspect it's going to be related to https://github.com/golang/tools/commit/f595fb5c9663ecbe1b08ae76e9c0a1b69cd0fa33.

That's certainly looking to be the case. Look at the current implementation of `IsDir` in `gosrc`:

https://github.com/golang/gddo/blob/936217787a75581223fdad5426c89f45df72b5dc/gosrc/build.go#L27

That's not valid, some paths are certainly directories. It was working anyway in previous versions of Go due to a bug, but that bug has been fixed, and it's causing this broken implementation to stop working. `IsDir` needs to return valid results now. I suspect that'll fix the problem.

**Comment by shantuo** [comment]
Yes, that is the problem.
Also I found
[https://github.com/golang/gddo/blob/936217787a75581223fdad5426c89f45df72b5dc/gosrc/build.go#L28](url)
Is this also a workaround of some bug?

**Comment by shurcooL** [comment]
Not that I know of. It's been like that since the first commit, see https://github.com/golang/gddo/blame/936217787a75581223fdad5426c89f45df72b5dc/gosrc/build.go#L28.

I suspect it's done that way for the same reason. Previously, a valid implementation of `HasSubdir` wasn't neccessary, so a no-op implementation was sufficient.

**Comment by shurcooL** [comment]
@shantuo What's our status here? I want to make sure this isn't blocked on me. Is there anything I can/should do to help make progress?

**Comment by shantuo** [comment]
Sorry I didn't have a chance to work on this this morning. It seems to me that using the default IsDir (os.Stat) should work? Am I understanding this correctly?

**Comment by shurcooL** [comment]
No problem.

As I understand, it should be a custom implementation that uses the data in the [`gosrc.Directory`](https://github.com/golang/gddo/blob/34ff3df85ae83c83da3ea7b1aa09fb5fc843c468/gosrc/gosrc.go#L49-L96). There wouldn't be files on disk.

**Comment by shurcooL** [comment]
Would it be helpful if I worked on a CL, or do you want to continue to take this?

**Comment by shantuo** [comment]
Sent golang.org/cl/59191, let me know if I got this right.
