### ISSUE TITLE
Getting 404 NotFound for a repo

### ISSUE THREAD

**Issue by jcmturner** [golang/gddo#514]
Hi,

I'm getting a 404 NotFound for this link: https://godoc.org/gopkg.in/jcmturner/gokrb5.v1

I can't see why this is as godoc is working perfectly for other repos I have such as https://godoc.org/gopkg.in/jcmturner/aescts.v1

Any help is greatly appreciated. Thanks.

**Comment by shurcooL** [comment]
Not seeing the issue, I get 200 OK.

![image](https://user-images.githubusercontent.com/1924134/31061341-32c02e88-a6ee-11e7-9c3e-fb906f3935e3.png)

**Comment by jcmturner** [comment]
Strange, is there some caching in godoc as it was a 404 until today?

I also notice that not all the directories are listed and they do not appear when I click "Refresh now"

Thanks...

**Comment by shantuo** [comment]
It shouldn't have any caching.

My guess would be that since this is a directory, not a package, it doesn't show anything until one of the subdirectory (which is a package) get crawled. gddo crawls one package a time, not a whole repo. I'm going to close this issue for now. Feel free to reopen if you have more questions. Thanks!
