### ISSUE TITLE
Packages disappeared from godoc.org

### ISSUE THREAD

**Issue by keks** [golang/gddo#561]
Hi, all packages under the domain go.cryptoscope.co vanished from godoc.org. They used to be there and are still returned in the search results, but the API documentation doesn't show. `ge get`ting to a fresh gopath works fine, and the html for e.g. https://go.cryptoscope.co/margaret/offset?go-get=1 looks correct:
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="go.cryptoscope.co/margaret git https://github.com/cryptoscope/margaret">
</head>
</html>
```

I asked in #go-nuts and others agreed this is most likely a bug in godoc.

**Comment by keks** [comment]
I'd be happy to help out with more info!

also cc @cryptix

**Comment by shantuo** [comment]
Hi,

The host is blocked since there were tens of thousands of spam subdirectories added to the crawler queue.
Those packages look like "go.cryptoscope.co/sbot/info/refs/message/repo/blobstore/blobstore/cmd/cmd/blobstore/repo/blobstore/message/blobstore", which clearly doesn't exist. I need to investigate more on the cause.
