### ISSUE TITLE
Search results for `strings` does not include the `strings` package.

### ISSUE THREAD

**Issue by dcormier** [golang/gddo#575]
[https://godoc.org/?q=strings](https://godoc.org/?q=strings) results do not include the `strings` package, though you can go to it [directly](https://godoc.org/strings).

![image](https://user-images.githubusercontent.com/216265/44872784-6f5ef000-ac64-11e8-8d37-b2298be0d633.png)

----

Edit: This is also true of searching for [`bytes`](https://godoc.org/?q=bytes).

**Comment by myitcv** [comment]
I think this is a dup of https://github.com/golang/gddo/issues/573

**Comment by dcormier** [comment]
Similar. Except searching for [`http`](https://godoc.org/?q=http) or [`net/http`](https://godoc.org/?q=net/http) currently works. Searching for [`strings`](https://godoc.org/?q=strings) still does not.

**Comment by dcormier** [comment]
Searching for [`bytes`](https://godoc.org/?q=bytes) also does not work right now.

**Comment by dmitshur** [comment]
At the bottom of both `strings` and `bytes` packages, there was an error:

![image](https://user-images.githubusercontent.com/1924134/45121869-5eb0ed00-b130-11e8-9146-3816e6fbc9a5.png)

![image](https://user-images.githubusercontent.com/1924134/45121883-696b8200-b130-11e8-899b-8266698a8a78.png)

I've refreshed both packages just now (with the currently deployed gddo version), and the no longer exhibit errors:

![image](https://user-images.githubusercontent.com/1924134/45121962-8e5ff500-b130-11e8-9884-dff8ef67752a.png)

![image](https://user-images.githubusercontent.com/1924134/45121972-95870300-b130-11e8-913a-aa893b09fdc2.png)

Those build errors were causing them to be excluded from the search results. Since the build errors are resolved now, the two packages show up in search:

![image](https://user-images.githubusercontent.com/1924134/45122030-ba7b7600-b130-11e8-82de-53991ccfcff1.png)

![image](https://user-images.githubusercontent.com/1924134/45122050-c5cea180-b130-11e8-88fb-2ddc4ce810f3.png)
