### ISSUE TITLE
Don't truncate package docs

### ISSUE THREAD

**Issue by broady** [golang/gddo#635]
From https://github.com/googleapis/google-api-go-client/issues/372

https://godoc.org/google.golang.org/api/compute/v0.beta and https://godoc.org/google.golang.org/api/compute/v1 both displays:

```
The documentation displayed here is incomplete. Use the godoc command to read the complete documentation.
```

instead of rendering the godoc for the packages.

**Comment by dmitshur** [comment]
The current document size limit is 800'000 bytes:

https://github.com/golang/gddo/blob/af0f2af80721261f4d211b2c9563f7b46b2aab06/database/database.go#L263-L264

The `compute/v0.beta` package document size is currently 1'004'901 bytes, and `compute/v1` is 834'564 bytes.

Instead of doubling the limit, I am considering going with a more conservative 1.5x multiplier and updating it to 1'200'000 bytes. If we need to exceed that limit further in the future, we can re-evaluate then.

/cc @shantuo @stephenmw
